= Spiseforstyrrelser 

== Om pakkeforløpet 
Se dokumentasjon her: https://helsedirektoratet.no/Documents/H%C3%B8ringer/Pakkeforl%C3%B8p%20for%20psykisk%20helse%20og%20rus/Spiseforstyrrelser%20hos%20barn%20og%20unge%20-%20pakkeforl%C3%B8p%20-%20h%C3%B8ringsutkast.pdf[]

== Hendelsesregistrering 

. Start pakkeforløp 
. Vurdering og beslutning om videre oppfølging
. Planlegging av behandling 
. Behandling ved spiseforstyrrelser hos barn og unge
. Evalueringspunkter 
. Håndtering av avbrudd i behandlingen 
. Avsluttende samtale 
. Overføring til annet helseforetak / privat behandlingssted

=== Hendelse:  Start pakkeforløp 
Pakkeforløp for spiseforstyrrelser skal startes når: 

. Henvisning vurderes og det er innenfor kravene til pakkeforløp 
. Begrunnet mistanke om spiseforstyrrelse inntreffer i spesialisthelsetjenesten 

Da skal det: 

. Startes pakkeforløp av typen _Pakkeforløp psykisk helse og rus_, 
. og den spesifikke typen er _D08 Spiseforstyrrelse - barn og unge_ 
. og dette markerer start av pakkeforløpet med kode _9322A_. 

I DIPS Arena er dette en oppføring av en INSTRUCTION av typen `openEHR-EHR-INSTRUCTION.trajectory.v1`, +
og elementet forløpstype (/activities[at0001]/description[at0002]/items[at0003]) settes med kodeverksverdi: +
`VOLVEN-9321::D08::Spiseforstyrrelse - barn og unge`


=== Hendelse: Vurdering og beslutning om videre forløp 
Kodeverket <<OID-9323, utfall klinisk beslutning>> definerer kodeverket for kliniske beslutninger. 

.Koder som benyttes inne spiseforstyrrelser.
[cols="^10,^10,80", options="header"]
|=== 
|Kode |Bruk | Beskrivelse
|U| -|	Behov for utvidet utredning	
|P|x |	Behov for behandling innen psykisk helsevern	
|T|x |	Behov for behandling innen TSB	
|S|x |	Behov for behandling fra annen spesialisthelsetjeneste (ikke Psykisk helsevern eller TSB)	
|K|x|	Behov for behandling og/eller oppfølging fra fastlege, kommunal helse- og omsorgstjeneste	
|A|x |	Behov for oppfølging fra andre instanser som NAV, PPT, arbeidsgiver, skole, barnevern mm.	
|I|x|	Ikke behov for videre behandling og/eller oppfølging
|===

== Behandling ved spiseforstyrrelser hos barn og unge 

.Se <<OID-9325>>
----
VOLVEN-9325::S::Familiebasert behandling spesifikt for spiseforstyrrelser
----

== Skjema 


På registersiden er det en opplisting av https://nordlandssykehuset.no/fag-og-forskning/kvalitetsregistre/norsk-kvalitetsregister-for-behandling-av-spiseforstyrrelser-norspis#enkeltskjema[enkeltskjema]. 


Bakgrunnsopplysninger (<15 år):: https://nordlandssykehuset.no/Documents/Fag%20og%20forskning/Kvalitetsregistre/NorSpis/Sp%C3%B8rreskjema%20-%20enkeltvis/Bakgrunnsopplysninger%20under%2015%20a%CC%8Ar%20NorSpis_v1.0.1.pdf[]


