== Implementasjon av pakkeforløp for kreft

The following describes the use-cases to implement 'pakkeforløp for Kreft' i DIPS Arena. 


== Phase 1: Use-cases
The following is the primary use-cases to be able to follow up cancer patients in a "pakkeforløp".

=== Create folder
[source]
----
Given that a user approve a composition that contains INSTRUCTION of type openEHR-EHR-INSTRUCTION.trajectory
And the trajectory type is defined as TrajectoryType:</activities[at0001]/description[at0002]/items[at0003]/value/value>

Then Arena should create a folder of type "TRAJECTORY:$TrajectoryType"
And the INSTRUCTION should be the header entry for the folder.
----

=== Patientlist with cancer trajectories 

[source]
----

Given that an administrator creates a new list of type FOLDER,
then the folder type combobox should display "CANCER TRAJECTORY" as an item to select,
and the patient list should list all folders of this type.
----

[source]
----

Given that a user has selected a row in folder patientlist,
and he creates a new openEHR entry on this row.
Then the document MUST be connected to the selected folder.
----

The openEHR patientlist provider must make it possible to have several columns based on the same Archetype, and there should be where clausuls to separate the columns.


|====
|Pakkeforløp | Start |  Biopsi | Første fremmøte | Klinisk beslutning | Start behandling
| A01::Brystkreft
|27.april (3 dager siden)
| I dag  
| Nå 
| CK::Klinisk beslutning; Organspesifikk kreft 
| Nå
|====


=== Close folder
[source]
----
Given that a user approve a composition that contains ACTION of type openEHR-EHR-ACTION.kreftpakke.v1,
and the composition belongs to the folder,
and the state of the Action is final state (cancel, abort or completed).
Then the folder should be closed.
----

WARNING: We must agree on if this should be connected to aggregated state of the INSTRUCTION or the current ACTIVITY.


=== "Pakkeforløp" in DIPS Classic
Most users will not use DIPS Arena in the next months. This means that Classic users also should know if a patient is in a "pakkeforløp" and he should be able to read information from it.

In Classic we must add a new menu button in the same way we added the "Kjernejournal" button. This is an interactive button which is loaded when the user activates the patient. Then it check if there are any active folders for the given patient. It there are active folders the button get activated and displays the number of active folders.

When the user click the button he get a list of all the active folders. Each active folder has a summary based on Unify. When he click on the active folder item Classic opens the summary.

The same module could also be added to Arena as a button on the patient line.

[source]
----
Given that the user has activated a patient in Classic 
and the patient has one ore more active 'Pakkeforløp'
Then Classic MUST display a button in active state
and the number of active 'Pakkeforløp' should be displayed. 
----

[source]
----
Given that the user click the button with active 'Pakkeforløp'
Then Classic should display a list of the active 'Pakkeforløp' items
and the user shold be able to click one of the 
and Classic will display a summary of all entries in the 'Pakkeforløp'
----

== Phase 2 use-cases

=== Generic folder tile

Arena must have a generic tile that list all folders for the given patient. By default all active folders should be available and the number of folders should be readable on the minimized tile.

Depending on the folder type there will be diffent kind of information to display. Each folder type should have its own configuration. This configuration is based on Arena Insight.

=== Health record metadata to connect each document to folder

Given that a user creates a new document in an EHR,
it must be possible to connect the document to one or more active folders.

This could be done from the Metadata panel in Healthrecord Client.

=== Add an episode of care to folder

It should be easy to add an episode of care ("kontakt") to an folder. This makes it possible to use the first episode of a given type to st the code "første fremmøte" in a "pakkeforløp".



== Dokumentflyt

* All registrering i samme dokument
* Registrering i flere dokument

=== All registrering i samme dokument

==== Fordeler

Ved å samle all dokumentasjon i ett forløpsdokument blir det enklere å forstå registreringen. Det er *bare* å hente opp det angitte dokumentet. Videre er det lett å knyttet et slik dokument til henvisningen.

Det samlede dokumentet kan lett skrives ut eller sendes elektronisk.

Rapporten til Helsedirektoratet forenkles ved å kun hente registreringer fra gitte dokumenttyper. Gjerne som AQL spørringer for Composition av en viss type.

==== Ulemper
Ikke så lett å avdekke hvilken bruker som har gitt de ulike bidragene. Workaround er å innføre et felt "oppført av" for hver hendelsesregistrering.

=== Registering i flere dokument

==== Fordeler
Oppføringene blir riktigere siden hver forfatter står ansvarlig for sitt bidrag.

Versjonering av hendelsesregistrering blir korrekt. Dette gjøres ved "normal" versjonering av dokumenter.

==== Ulemper
Det må utvikles egen løsning for sammendrag av pakkeforløpet. Denne visningen må hente inn alle relevante registreringer.

Litt vanskeliger å koble gjeldende pakkeforløp med hendelsene. I løsning med ett dokument vil alltid gjeldende pakkeforløp finnes i samme dokument. I løsning med flere dokumenter kan vi velge å referere gjeldende pakkeforløp. Enten via generisk felt som ikke lagres i journalen, eller ved å gjenbruke gjeldende registrering og la brukeren lagre dette sammen med sine registreringer.


== Running notes 


En henvisningsperiode har potensielt flere kreftpakkeforløp. OUS benytter sekundær henvisning for ulike forløp. F.eks. for utredning nedre gastro.


Påstand:: Alle pakkeforløp er sekundærhenvisninger som startes med en INSTRUCTION.

Problem:: Mye av datagrunnlaget er sekundær data, dvs. det kommer fra andre oppføringer. Som f.eks. første kontakt i et forløp eller første biopsi i et forløp. Samtidig er det vanskelig å definere hva et forløp er slik at vi kan ha en konkret plattform å trekke data ut fra.

Sak:: Vi må ha sak for pakkeforløp. Slik at dokumenter og kontakter knyttes til sak. På den måten kan vi sammenstille informasjon fra mange datakilder og sammenstille til rapport.

Spørsmål:: Kan kontakter knyttes til saker?

Må også:: Kunne se hva som er bestilt ; f.eks. MR etc.

Arbeidsflyt:: Hva med varsling når pasienter er i ferd med å skli ut av forløp, dvs. når tidsfrister er i ferd med å gå over.


== Problem areas



=== How can we make it "dead simple" to connect entries (documents) to the correct context?

In Arena we have several layers of context for a given patient.

* EHR
** Periode of care
*** Episode of care
* Folder





=== INSTRUCTION vs. ACTIVITY
To be able to connect ACTION entries to an ACTIVITY each ACTION entry must store the ID to the ACTIVITY. This means that the context when creating a new ACTION must have information about the ACTIVITY.



What is the id of the ACTIVITY?

Each ACTION has a field named _instruction details_. This field contains the following attributes:

Instruction id:: the path to the instruction as a Locatable Ref.
Activity id :: the id of the activity
Worfklow details:: a structure that defines the workflow definition



== Form 

Calculation 

[source]
-----
ISO8601DATE(DATEVALUE(start)+DAYTICKS(daysToPhaseOne+daysToPhaseTwo+daysToPhaseThree))

-----