// Dette er DIPS sin mal for brukerdokumentasjon (asciidoc).
// Målgruppen for dette dokumentet er sluttbrukere/superbrukere/forvaltere.
// Dokumenter basert på denne malen vil normalt ha "user_<programpakke (engelsk)>.adoc" som filnavn


:imagesdir: images


:dips-template-url: .
include::{dips-template-url}\styles\dips-core-styles.adoc[]
include::{dips-template-url}\styles\dips-style-no.adoc[]


:product: Arena Pasienttavle
:documenttype: Brukerdokumentasjon


ifdef::backend-pdf[= {product}: {documenttype}]
ifdef::backend-html5[= {product} +++<BR>+++{documenttype}]
DIPS AS
:revnumber: Versjon 1.0
:revdate: 2019-04-11
:revremark: 

include::{dips-template-url}\styles\print.adoc[]

ifdef::print[]
include::{dips-template-url}\content\dips-copyright-notice.adoc[]

[[dips-document-history]]
[discrete]
#### Historikk
[options="header",frame="topbot",cols="15,10,20,55"]
|===
|Dato		|Revisjon	|Forfatter	|Beskrivelse
|YYYY-MM-DD |1.0	|navn		|Kort beskrivelse av endring(er) i dokumentet som gjør det mulig for leseren å se hva som er nytt/endret ml. revisjoner.
|===

endif::[]

<<<

ifeval::["{revremark}"=="Foreløpig"]
include::{dips-template-url}\content\dips-prerelease-notice-no.adoc[]
endif::[]


[[CONTENT]]

// tag for context sensitive hjelp
// tag::includetext[]

:product: <produktnavn (NO)>
:Config_Product_Oppsett_konfig-doc:

////
Se wiki https://wiki/Documentation-guidelines/Veiledning-for-brukerdokumentasjon for nærmere beskrivelse.

For å lage et anker, sett to hakeklammer foran og bak:

[[productnameanchor]]

og legg det over overskriften som du vil linke til, med ett linjeskift mellom, f.eks. slik:

[[arenadocumentsscanningnewdocuments]]

==== Skanne dokumenter

Det er støtte...

////

[[productnameanchor]]


_Relativt kort beskrivelse av konseptet. Konseptuell - HVA er dette - det skal ikke stå noe her om HVORDAN. I tillegg skal du lime inn et hovedskjermbilde som illustrasjon. +
Dette skal skrives med en positiv vinkling på produktet og skal også kunne brukes som salgsmateriale av markedsavdelingen. Dette kapitlet vil også kunne bli oppdatert av markedsavdelingen_

[[productnameanchorwhatisquickguide]]

== Hurtiginnføring for {product}

Arena Logistics Dashboard gir oversikt over hvordan situasjonen er på en avdeling. Der kan du med ett blikk se hvem som er inneliggende på avdelingen, og om det er noen pasienter som krever spesialtiltak. Den inneholder også klinisk informasjon som er viktig for å vurdere evt. risiko som pasienter har, slik at behandler kan planlegge viktige tiltak og oppfølging. Dashboardet skal sette rammen for tverrfaglig samhandling hver dag. Det bidrar til mer effektiv drift, at helsepersonell er mer obs på hvilke tegn og farer de skal se etter, og hvilke tiltak de skal iverksette.
 
Arena Logistics Dashboard kan brukes på følgende måte:

=== Avdelingskoordinator: 

For koordinering f.eks. tildeling av ressurser til rett pasient, romtildeling, tildeling av oppgaver og kvalitetssikring.

=== Sykepleier og lege: 

For å få en rask oversikt over situasjonen og orientere seg på avdelingen når man kommer på jobb eller tiltrer vakt.

=== Andre yrkesgrupper: 

For raskt å finne sine pasienter og samtidig ha oversikt over viktige egenskaper og risikofaktorer hos denne pasienten. 

=== Deloppgaver

_Bør være mulig å skrive ut på en A4-side. Merk: Denne danner samtidig en nyttig disposisjon for den detaljerte beskrivelsen. Tabellen under har overskrifter som er førende for hva som skal inngå._

.Hurtiginnføring
[options="header",frame="topbot",grid="none",cols="25,75"]
|===
|Oppgave |Hvordan?

|<Deloppgave 1>
|Beskrivelse av deloppgave 1

|<Deloppgave 2>
|Beskrivelse av deloppgave 2
|===

[[productnameanchorwhatisshortcuts]]

=== Hurtigtaster

.Hurtigtaster i hovedskjermbildet
[options="header", cols="40,80"]
[grid="none",frame="none"]
|===
|Hurtigtast |Funksjon
|kbd:[Ctrl+A] |Beskrivelse av hurtigtast
|kbd:[Ctrl+Shift+A] |Beskrivelse av hurtigtast
|kbd:[Alt+A] |Beskrivelse av hurtigtast
|kbd:[Tab+1] |Beskrivelse av hurtigtast
|===

[[productnameanchormenucelection_buttons]]

=== Menyvalg og knapper

.Menyvalg i hovedskjermbildet
[options="header", cols="40,80"]
[grid="none",frame="none"]
|===
|Menyvalg |Funksjon
|menu:Vis[Zoom > Nullstill] |Beskrivelse av menyvalg
|menu: |Beskrivelse av menyvalg
|===

.Knapper i hovedskjermbildet
[options="header", cols="40,80"]
[grid="none",frame="none"]
|===
|Knapp |Funksjon
|btn:[Avbryt] |Beskrivelse av knapp
|btn:[] |Beskrivelse av knapp
|===

[[productnameanchorwhatisterminology]]

=== Begreper

_Her forklares viktige begreper_

include::UTV Mal concepts.adoc[]

_Legg gjerne til andre tabeller ved behov_


[[productnameanchorhowtouse]]

== Bruke {product}

[[productnameanchorhowtouseareasforuse]]

=== Godkjente bruksområder

_I dette avsnittet beskrives i korte trekk hvordan produktet/funksjonen/modulen er ment å anvendes. F.eks vil godkjente bruksområder for «Vekstkurve» kunne beskrives som følgende: «Vekstkurve er ment for oppfølging av vekten til barn som er mellom 0-18 år». Med dette vil man utelukke at «Vekstkurve» f.eks anvendes til å følge utvikling av voksne menns overvekt. Dette fordi det kun er de bruksområder som er dokumentert fra vår side som inngår i vårt vedlikeholdsansvar for funksjonaliteten_

[[productnameanchorhowtousetask1]]

=== <Gjøre deloppgave 1>

_Overskriften skal stå med verbet i infinitiv, for eksempel «Registrere ny pasient», «Bruke oppmøtelista» eller «Rekvirere lab-prøver»._

_NB! Rutinen skal dekke behovene både for et papirbasert sykehus og et papirløst sykehus (med EPJ). Bør presentere det vi anbefaler, men også vise hva som er alternative måter._

_Rutinene skal presenteres detaljert med punktvise fremgangsmåter og målet er å inkludere færrest mulig skjermbilder (for å minske behovet for vedlikehold og fordi brukeren høyst sannsynlig har DIPS oppe samtidig som han leser hjelpeteksten). Referanser til feltnavn, knapper og skjermbilder skal stå med stilen DIPS Felt (for eksempel: «Klikk på OK»)_

[[productnameanchorhowtousetask1screendumps]]

==== Skjermbildereferanser

_Skjermbildereferansene kommer etter den rutinen skjermbildet beskrives brukt i og hvis det samme skjermbildet beskrives brukt i en senere rutine så henviser Skjermbildereferansene etter den senere rutinen oppover_

[[productnameanchorhowtousetask1screendump1]]

.Skjermfeltbeskrivelser
[options="header",frame="topbot",grid="none",cols="25,75"]
|===
|Skjermelement |Beskrivelse

|<Felt 1>
|Beskrivelse av feltet, inkludert referanse til aktuelt kodeverk eller
offentlig regelverk som styrer bruken av feltet

|<Knapp 1>
|Beskrivelse av knappens funksjon og bruksområde

|<Kolonne 1>
|Beskrivelse av kolonnen, inkludert referanse til eventuelt kodeverk
|===

_Hurtigtaster tas bare med dersom det finnes egne hurtigtaster som ikke er beskrevet under hovedskjermbildet._

[[productnameanchorhowtousetask1screendump1shortcuts]]

.Hurtigtaster
[options="header", cols="20,80"]
[grid="none",frame="none"]
|===
|Hurtigtast |Funksjon
|kbd:[Ctrl+A] |Beskrivelse av hurtigtast
|kbd:[Ctrl+Shift+A] |Beskrivelse av hurtigtast
|kbd:[Alt+A] |Beskrivelse av hurtigtast
|kbd:[Tab+1] |Beskrivelse av hurtigtast
|===

_Det anbefales at det beskrives neste naturlige brukte modul/funksjon/prosess og at det legges inn linker til brukerdokumentasjon som det refereres til._

_Husk: Det er viktig med korrekt navngiving av link som legges inn. Eks: «Journal|Bruke Journaldokumenter» ved henvisning til et bestemt kapittel i brukerdokumentasjonen_

[[productnameanchorhowtousetask2]]

=== <Gjøre deloppgave 2>

[[productnameanchorhowtousetask2screendumps]]

==== Skjermbildereferanser


=== Tips til problemløsning

_Dette punktet tas med hvis det er relevant. Dette kan for eksempel være ting som kunder stadig ringer brukerstøtte om. Formuler fremgangsmåtene som nummererte lister._

==== Beskrivelse av problem 1

==== Ofte stilte spørsmål

_Her skal korte spørsmål (i fet skrift) og svar (i normal skrift) ramses opp._

_Hvis svaret innebærer en framgangsmåte så skal nummererte lister benyttes._

[qanda]
Spørsmål 1::
  Svar 1
Spørsmål 2::
  * Gjør først dette
  * Gjør så dette
  * Avslutt med dette


//Arbeidsflyt

//Dette skal beskrives i eget dokument som inkluderes/lenkes inn i brukerdokumentet. Bruk malen "UTV Mal Bruker Arbeidsflyt.adoc" og ev. flytdiagram, det foreligger også maler for flytdiagram.

// Oppsett, konfigurasjon og tilgangskontroll

// Dette skal beskrives i eget dokument som inkluderes/lenkes inn i brukerdokumentet. Bruk malen "UTV Mal Bruker Oppsett og konfigurasjon.adoc"


//// 
Start include for dokument Config_Product_Oppsett_konfig-doc. Eget dok. for oppsett og konfigurasjon av konfigurerte produkter som inkl. dersom det er aktuelt.

ifdef::Config_Product_Oppsett_konfig-doc[]

include::{Config_Product_Oppsett_konfig-doc}[tags=Oppsett_og_Konfig1]
include::{Config_Product_Oppsett_konfig-doc}[tags=Oppsett_og_Konfig2]
endif::[]

End include Config_Product_Oppsett_konfig-doc
////

//slutt på tag for context sensitive hjelp

//end::includetext[]

ifdef::backend-html5[]
<<<
include::{dips-template-url}\content\dips-copyright-notice.adoc[]
endif::[]
