[[D03]]
= D03 Utredning av psykiske lidelser – voksne

== Om pakkeforløpet 

Pakkeforløpet omhandler utredning av moderat til alvorlig psykisk lidelse. Dersom pasienten har kjent psykisk lidelse bør det henvises direkte til <<D05, behandling>>

Beskrivelse 
https://helsedirektoratet.no/Documents/NFR/pakkeforl%C3%B8p%20psykisk%20helse%20og%20rus/Utredning%20av%20psykiske%20lidelser%20hos%20voksne%20%E2%80%93%20pakkeforl%C3%B8p%20-%20h%C3%B8ringsutkast.pdf[]

== Målepunkter 
Forløpstidene følges ved at følgende hendelser kodes: 

* Henvisning mottatt
* Henvisning vurdert 
* Første fremmøte 
* Basis utredning: Beslutning om videre tiltak 
* Utvidet utredning: Beslutning om videre tiltak 
* Avbrudd

NOTE: Henvisning mottatt og vurdert er målepunkter. Dersom pakkeforløpet starter etter at disse målepunktene er ferdig må a) brukeren legge inn disse tidene retrospektivt eller b) systemet henter de ut fra administrative data. 

== Forløpstider og hendelser 

|=== 
|Fra | Til | Frist 
|Første fremmøte | Basis utredning utført | 6 uker 
|Beslutning om behov for utvidet utredning | Utvidet utredning avsluttet | 6 uker 
|===


include::event_first_encounter.adoc[leveloffset=+1]

=== Basis utredning utført 

[horizontal]
Hendelse:: <<OID-9322, 9322>>::U::Utført aktivitet 
Utfall:: <<OID-9325, 9325>> ??

WARNING: Hvordan kode basis utredning utført? Det finnes ingen kode for dette utfallet

=== Behov for utvidet utredning
Beslutning om behov for utidet utredning skal kodes med kode for hendelse og utfall. Hendelsen er *<<OID-9322,9322>>::C::Klinisk beslutning_*  og utfallet er *<<OID-9323,9323>>::U::Behov for utvidet utredning*

=== Utført utvidet utredning
Utført utvidet utredning kodes med kode for hendelse og utfall: 
* Hendelse er *<<OID-9322, 9322>>::U::Utført aktivitet* 
* Utfall er *<<OID-9325, 9325>> 

WARNING: Finner ingen kode i <<OID-9325>> som definerer at utvidet utredning er ferdig 

