:imagesdir: images 

= Follow up on stroke ward 

== Background 
Given a patient with stroke or suspected stroke. Then the  following four tasks should be performed during the stay: 

* <<MRS-SCORE>>
* <<SWALLOW-SCORE>>
* <<BARTHEL-SCORE>>
* <<NIHSS-SCORE>>

The tasks should be outlined in the following protocol. 

NOTE: There is one screening for each of the first six days and then at the discharge. 

.Day 0 (Admission)
* mRS at admission
* Swallow test

.Day 1
* NIHSS 
* Barthel

.Day 2
* NIHSS

.Day 3 
* NIHSS
* Barthel 

.Day 4 
* NIHSS 

.Day 5 
* NIHSS
* Barthel 

.At discharge
* mRS at discharge 
* NIHSS
* Barthel 




== Description of the tests
In the following you will find some more info about the different tests/scores. 

[[SWALLOW-SCORE]]
=== Swallow test

* http://www.helsebiblioteket.no/retningslinjer/hjerneslag/vedlegg/tester/test-svelgefunksjon;jsessionid=92E904D8FA0136BE20F8791DC4C6101E?tabkey=5[Helsebiblioteket - test av svelgfunksjon]
* https://www.ncbi.nlm.nih.gov/pubmed/23548854[Water-swallowing test: screening for aspiration in stroke patients.]

[[BARTHEL-SCORE]]
=== Barthel Index
Archetype: http://www.openehr.org/ckm/#showArchetype_1013.1.128[openEHR-CKM]

Concept:: Barthel index of dependency in activities of daily living.

Purpose:: To record a score of dependency on help to undertake important activities of daily living. The total score is the sum of the ordinal scores for each attribute.


[[NIHSS-SCORE]]
=== National Institutes of Health (NIH) Stroke Scale

* http://emedicine.medscape.com/article/2172609-overview[Medscape]
* https://www.mdcalc.com/nih-stroke-scale-score-nihss[MDCalc]

When to use:: The NIHSS can help physicians quantify the severity of a stroke in the acute setting.

Why use:: There are nearly 800,000 cases of acute stroke in the United States every year, with 130,000 associated deaths (4th leading cause of death in Americans).
+
The NIHSS can help physicians determine the severity of a stroke, predict clinical outcomes.


==== 1a. Level of consciousness: 
The investigator must choose a response, even if a full evaluation is prevented by such obstacles as an endotracheal tube, language barrier, or orotracheal trauma/bandages. A 3 is scored only if the patient makes no movement (other than reflexive posturing) in response to noxious stimulation.	

0 = Alert; keenly responsive
1 = Not alert, but arousable by minor stimulation to obey, answer, or respond
2 = Not alert, requires repeated stimulation to attend, or is obtunded and requires strong or painful stimulation to make movements (not stereotyped)
3 = Responds only with reflex motor or autonomic effects or is totally unresponsive, flaccid, or areflexic

==== 1b. Level of consciousness questions: 
The patient is asked the month and his/her age. The answer must be correct; no partial credit is given for being close. Aphasic and stuporous patients who do not comprehend the questions are given a score of 2. Patients unable to speak because of endotracheal intubation, orotracheal trauma, severe dysarthria from any cause, language barrier, or any other problem not due to aphasia are given a 1. It is important that only the initial answer be graded and that the examiner not "help" the patient with verbal or nonverbal cues.

* 0 = Answers both questions correctly
* 1 = Answers one question correctly
* 2 = Answers neither question correctly

==== 1c. Level of consciousness commands: 
The patient is asked to open and close the eyes and then to grip and release the nonparetic hand. Substitute another one-step command if the hands cannot be used. Credit is given if an unequivocal attempt is made but not completed because of weakness. If the patient does not respond to command, the task should be demonstrated to him/her (pantomime) and the result scored (ie, follows none, one, or two commands). Patients with trauma, amputation, or other physical impediments should be given suitable one-step commands. Only the first attempt is scored.	

* 0 = Performs both tasks correctly
* 1 = Performs one task correctly
* 2 = Performs neither task correctly

==== 2. Best gaze: 
Only horizontal eye movements are tested. Voluntary or reflexive (oculocephalic) eye movements are scored, but caloric testing is not performed. If the patient has a conjugate deviation of the eyes that can be overcome by voluntary or reflexive activity, the score will be 1. If a patient has an isolated peripheral nerve paresis (CN III, IV, or VI), score a 1. Gaze is testable in all aphasic patients. Patients with ocular trauma, bandages, or pre-existing blindness or other disorder of visual acuity or fields should be tested with reflexive movements and a choice made by the investigator. Establishing eye contact and then moving about the patient from side to side occasionally clarifies the presence of a partial gaze palsy.	

* 0 = Normal
* 1 = Partial gaze palsy; gaze is abnormal in one or both eyes, but forced deviation or total gaze paresis is not present.
* 2 = Forced deviation, or total gaze paresis not overcome is by the oculocephalic maneuver

==== 3. Visual:
Visual fields (upper and lower quadrants) are tested by confrontation, using finger counting or visual threat as appropriate. The patient must be encouraged, but if he/she looks at the side of the moving fingers appropriately, this can be scored as normal. If is the patient has unilateral blindness or enucleation, visual fields in the remaining eye are scored. Score 1 only if a clear-cut asymmetry, including quadrantanopia, is found. If the patient is blind from any cause, score 3. Double simultaneous stimulation is performed at this point. If there is extinction, the patient receives a 1 and the results are used to answer question 11.	0 = No visual loss

* 1 = Partial hemianopia
* 2 = Complete hemianopia
* 3 = Bilateral hemianopia (blind including cortical blindness)

==== 4. Facial palsy: 
Ask or use pantomime to encourage the patient to show teeth or raise eyebrows and close eyes. Score symmetry of grimace in response to noxious stimuli in the poorly responsive or noncomprehending patient. If facial trauma/bandages, orotracheal tube, tape, or other physical barrier obscures the face, these should be removed to the extent possible.	0 = Normal symmetrical movements

1 = Minor paralysis (flattened nasolabial fold, asymmetry on smiling)
2 = Partial paralysis (total or near-total paralysis of lower face)
3 = Complete paralysis of one or both sides (absence of facial movement in the upper and lower face)

==== 5. Motor arm: 
The limb is placed in the appropriate position: extend the arms (palms down) 90° (if sitting) or 45° (if supine). Drift is scored if the arm falls before 10 seconds. The aphasic patient is encouraged using urgency in the voice and pantomime, but not noxious stimulation. Each limb is tested in turn, beginning with the nonparetic arm. The examiner should record the score as untestable (UN) only in the case of amputation or joint fusion at the shoulder and clearly write the explanation for this choice.	0 = No drift; limb holds 90° (or 45°) for full 10 seconds

* 1 = Drift; limb holds 90° (or 45°), but drifts down before full 10 seconds; does not hit bed or other support
* 2 = Some effort against gravity; limb cannot get to or maintain (if cued) 90° (or 45°), drifts down to bed, but has some effort against gravity
* 3 = No effort against gravity; limb falls
* 4 = No movement
* UN = Amputation or joint fusion 


===== 5a. Left Arm 

===== 5b. Right Arm 



====  Motor leg: 
The limb is placed in the appropriate position: hold the leg at 30° (always tested supine). Drift is scored if the leg falls before 5 seconds. The aphasic patient is encouraged using urgency in the voice and pantomime, but not noxious stimulation. Each limb is tested in turn, beginning with the nonparetic leg. The examiner should record the score as untestable (UN) only in the case of amputation or joint fusion at the shoulder and clearly write the explanation for this choice.	

* 0 = No drift; leg holds 30° position for full 5 seconds
* 1 = Drift; leg falls by the end of the 5-second period but does not hit bed
* 2 = Some effort against gravity; leg falls to bed by 5 seconds, but has some effort against gravity
* 3 = No effort against gravity, leg falls to bed immediately
* 4 = No movement
* UN = Amputation, joint fusion 



===== 6a. Left Leg 

===== 6b. Right Leg 


==== Limb ataxia:
This step is aimed at finding evidence of a unilateral cerebellar lesion. Test with the patient’s eyes open. In case of visual defect, ensure testing is done in intact visual field. The finger-nose-finger and heel-shin tests are performed on both sides, and ataxia is scored only if present out of proportion to weakness. Ataxia is absent in the patient who cannot understand or is paralyzed. Only in the case of amputation or joint fusion may the item be scored as untestable (UN), and the examiner must clearly write the explanation for not scoring. In case of blindness test by touching nose from extended arm position.	

* 0 = Absent
* 1 = Present in one limb
* 2 = Present in two limbs
* UN = Amputation or joint fusion

==== 8. Sensory: 
Sensation or grimace to pinprick when tested or withdrawal from noxious stimulus in the obtunded or aphasic patient. Only sensory loss attributed to stroke is scored as abnormal, and the examiner should test as many body areas (arms [not hands], legs, trunk, face) as needed to accurately check for hemisensory loss. A score of 2, "severe or total sensory loss," should be given only when a severe or total loss of sensation can be clearly demonstrated. Stuporous and aphasic patients will therefore probably score 1 or 0. The patient with brain stem stroke who has bilateral loss of sensation is scored 2. If the patient does not respond and is quadriplegic, score 2. Patients in coma (item 1a=3) are automatically given a 2 on this item.	

* 0 = Normal; no sensory loss.
* 1 = Mild to moderate sensory loss; patient feels pinprick is less sharp or is dull on the affected side or there is a loss of superficial pain with pinprick but patient is aware he/she is being touched
* 2 = Severe to total sensory loss; patient is not aware of being touched in the face, arm, and leg

==== 9. Best language:
A great deal of information about comprehension is obtained during the preceding sections of the examination. The patient is asked to describe what is happening in the given picture (see http://www.ninds.nih.gov/doctors/NIH_Stroke_Scale_Booklet.pdf[NIH_Stroke_Scale_Booklet.pdf]), to name the items on the given naming sheet, and to read from the given list of sentences. 

Comprehension is judged from responses here, as well as to all of the commands in the preceding general neurological examination. If visual loss interferes with the tests, ask the patient to identify objects placed in the hand, repeat, and produce speech. The intubated patient should be asked to write. The patient in coma (question 1a=3) will automatically score 3 on this item. The examiner must choose a score in the patient with stupor or limited cooperation, but a score of 3 should be used only if the patient is mute and follows no one-stepcommands.

* 0 = No aphasia; normal
* 1 = Mild to moderate aphasia; some obvious loss of fluency or facility of comprehension, without significant limitation on ideas expressed or form of expression; reduction of speech and/or comprehension, however, makes conversation about provided material difficult or impossible. For example, in conversation about provided materials, examiner can identify picture or naming card from patient's response
* 2 = Severe aphasia; all communication is through fragmentary expression; great need for inference, questioning, and guessing by the listener. Range of information that can be exchanged is limited; listener carries burden of communication. Examiner cannot identify materials provided from patient response
* 3 = Mute; global aphasia; no usable speech or auditory comprehension

=== 10. Dysarthria:
If patient is thought to be normal, an adequate sample of speech must be obtained by asking the patient to read or repeat words from a given list (http://www.ninds.nih.gov/doctors/NIH_Stroke_Scale_Booklet.pdf). If the patient has severe aphasia, the clarity of articulation of spontaneous speech can be rated. Only if the patient is intubated or has other physical barrier to producing speech may the item be scored as untestable (UN), and the examiner must clearly write an explanation for not scoring. Do not tell the patient why he/she is being tested.	

* 0 = Normal
* 1 = Mild to moderate; patient slurs at least some words and, at worst, can be understood with some difficulty
* 2 = Severe; patient's speech is so slurred as to be unintelligible in the absence of or out of proportion to any dysphasia, or is mute/anarthric
* UN = Intubated or other physical barrier

==== 11. Extinction and inattention (formerly neglect):
Sufficient information to identify neglect may be obtained during the prior testing. If the patient has a severe visual loss preventing visual double simultaneous stimulation and the cutaneous stimuli are normal, the score is normal. If the patient has aphasia but does appear to attend to both sides, the score is normal. The presence of visual spatial neglect or anosognosia may also be taken as evidence of abnormality. Since the abnormality is scored only if present, the item is never untestable.	

* 0 = No abnormality
* 1 = Visual, tactile, auditory, spatial, or personal inattention or extinction to bilateral simultaneous stimulation in one of the sensory modalities
* 2 = Profound hemi-inattention or hemi-inattention to more than one modality; does not recognize own hand or orients to only one side of space

.NIH Stroke Scale Scoring and Interpretation
[cols="^1, 10", options="header"]
|====
|Score|	Description
|0 |	No stroke
|1-4	|Minor stroke
|5-15 |Moderate stroke
|15-20	|Moderate/severe stroke
|21-42	|Severe stroke
|====

[[MRS-SCORE]]
=== Modified Rankin Scale (mRS)

The modified Rankin Scale (mRS) is a commonly used scale for measuring the degree of disability or dependence in the daily activities of people who have suffered a stroke or other causes of neurological disability. It has become the most widely used clinical outcome measure for stroke clinical trials. (https://en.wikipedia.org/wiki/Modified_Rankin_Scale[Wikipedia])

//The scale was originally introduced in 1957 by Dr. John Rankin of Stobhill Hospital, Glasgow, Scotland,[1][2] and then modified to its currently accepted form by Prof. C. Warlow's group at Western General Hospital in Edinburgh for use in the UK-TIA study in the late 1980s.[3] The first publication of the current modified Rankin Scale was in 1988 by van Swieten, et al., who also published the first interobserver agreement analysis of the modified Rankin Scale.[4]

//Interobserver reliability of the mRS can be improved by using a structured questionnaire during the interview process[5][6] and by having raters undergo a multimedia training process.[7] The multimedia mRS training system which was developed by Prof. K. Lees' group at the University of Glasgow is available online. The mRS is frequently criticized for its subjective nature which is viewed as skewing results, but is used throughout hospital systems to assess rehabilitation needs and outpatient course. These criticisms were addressed by researchers creating structured interviews which ask simple questions both the patient and/or the caregiver can respond to.[5][8]

//More recently, several tools have been developed to more systematically determine the mRS, including the mRS-SI,[9] the RFA,[10] and the mRS-9Q.[11] The mRS-9Q is in the public domain and a free web calculator is available at www.modifiedrankin.com.

.As described in http://www.strokecenter.org/wp-content/uploads/2011/08/modified_rankin.pdf[]
[cols="1,10", options="header"]
|====
|Score| Description
|0
|No symptoms at all
|1
|No significant disability despite symptoms; able to carry out all usual duties and activities
|2
|Slight disability; unable to carry out all previous activities, but able to look after own affairs
without assistance
|3
|Moderate disability; requiring some help, but able to walk without assistance
|4
|Moderately severe disability; unable to walk without assistance and unable to attend to own bodily
needs without assistance
|5 
|Severe disability; bedridden, incontinent and requiring constant nursing care and attention
|6 
|Dead
|====

TOTAL (0–6): _______